name: Latest medium activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-medium:
    name: Update this repo's README with latest activity from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM"
          feed_list: "https://medium.com/feed/@florian.schleuss"